const minions = [
  {
    "Name":"B-a-a-d Billy Gruff",
    "Alignment":"Evil",
    "Type":"Animal",
    "Tier":2,
    "Attack":2,
    "Health":3,
    "Gold Attack":4,
    "Gold Health":6,
    "Text":"",
    "Gold Text":"",
    "Keywords":"",
    "Combined":"Evil, Animal"
  },
  {
    "Name":"Baby Dragon",
    "Alignment":"",
    "Type":"Dragon",
    "Tier":2,
    "Attack":3,
    "Health":2,
    "Gold Attack":6,
    "Gold Health":4,
    "Text":"Flying",
    "Gold Text":"Flying",
    "Keywords":"Flying",
    "Combined":"Dragon, Flying"
  },
  {
    "Name":"Baby Root",
    "Alignment":"Good",
    "Type":"Treant",
    "Tier":2,
    "Attack":0,
    "Health":3,
    "Gold Attack":0,
    "Gold Health":6,
    "Text":"Support: +3 Health",
    "Gold Text":"Support: +6 Health",
    "Keywords":"Support",
    "Combined":"Good, Treant, Support"
  },
  {
    "Name":"Black Cat",
    "Alignment":"Evil",
    "Type":"Animal",
    "Tier":2,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"Last Breath: Summon a 1\/1 Cat.",
    "Gold Text":"Last Breath: Summon a 2\/2 Cat.",
    "Keywords":"Last Breath",
    "Combined":"Evil, Animal, Last Breath"
  },
  {
    "Name":"Blind Mouse",
    "Alignment":"",
    "Type":"Animal",
    "Tier":2,
    "Attack":2,
    "Health":2,
    "Gold Attack":4,
    "Gold Health":4,
    "Text":"Find 3 Blind Mice to get a level 4 treasure instead of level 2",
    "Gold Text":"",
    "Keywords":"",
    "Combined":"Animal"
  },
  {
    "Name":"Cinder-Ella",
    "Alignment":"",
    "Type":"Princess Mage",
    "Tier":2,
    "Attack":2,
    "Health":2,
    "Gold Attack":4,
    "Gold Health":4,
    "Text":"Quest: Cast 5 spells.",
    "Gold Text":"Quest: Cast 5 spells.",
    "Keywords":"Quest",
    "Combined":"Princess Mage, Quest"
  },
  {
    "Name":"Crafty",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":2,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"+3\/+3 for each Treasure you have.",
    "Gold Text":"+6\/+6 for each Treasure you have.",
    "Keywords":"",
    "Combined":"Dwarf"
  },
  {
    "Name":"Fanny",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":2,
    "Attack":2,
    "Health":2,
    "Gold Attack":4,
    "Gold Health":4,
    "Text":"Dwarf Support: +2\/+2",
    "Gold Text":"Dwarf Support: +4\/+4",
    "Keywords":"Support",
    "Combined":"Dwarf, Support"
  },
  {
    "Name":"Golden Chicken",
    "Alignment":"",
    "Type":"Animal",
    "Tier":2,
    "Attack":2,
    "Health":2,
    "Gold Attack":4,
    "Gold Health":4,
    "Text":"I sell for 2 Gold.",
    "Gold Text":"I sell for 4 Gold.",
    "Keywords":"",
    "Combined":"Animal"
  },
  {
    "Name":"Happy Little Tree",
    "Alignment":"Good",
    "Type":"Treant",
    "Tier":2,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"After each brawl, I gain +2 Health permanently.",
    "Gold Text":"After each brawl, I gain +4 Health permanently.",
    "Keywords":"",
    "Combined":"Good, Treant"
  },
  {
    "Name":"Humpty Dumpty",
    "Alignment":"Good",
    "Type":"Egg",
    "Tier":2,
    "Attack":6,
    "Health":6,
    "Gold Attack":12,
    "Gold Health":12,
    "Text":"When I die, I can't be put back together again.",
    "Gold Text":"When I die, I can't be put back together again.",
    "Keywords":"",
    "Combined":"Good, Egg"
  },
  {
    "Name":"Kitty Cutpurse",
    "Alignment":"Evil",
    "Type":"Animal",
    "Tier":2,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"Slay: +1 Gold",
    "Gold Text":"Slay: +2 Gold",
    "Keywords":"Slay",
    "Combined":"Evil, Animal, Slay"
  },
  {
    "Name":"Labyrinth Minotaur",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":2,
    "Attack":5,
    "Health":1,
    "Gold Attack":10,
    "Gold Health":2,
    "Text":"Your other Evil characters have +1 Attack.",
    "Gold Text":"Your other Evil characters have +2 Attack.",
    "Keywords":"",
    "Combined":"Evil, Monster"
  },
  {
    "Name":"Lonely Prince",
    "Alignment":"Good",
    "Type":"Prince",
    "Tier":2,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"When you buy a Princess, I transform into a 5\/5 Frog Prince.",
    "Gold Text":"When you buy a Princess, I trasnform into a 10\/10 Frog Prince.",
    "Keywords":"",
    "Combined":"Good, Prince"
  },
  {
    "Name":"Mad Mim",
    "Alignment":"Evil",
    "Type":"Mage",
    "Tier":2,
    "Attack":0,
    "Health":3,
    "Gold Attack":0,
    "Gold Health":6,
    "Text":"Support: +3 Attack",
    "Gold Text":"Support: +6 Attack",
    "Keywords":"Support",
    "Combined":"Evil, Mage, Support"
  },
  {
    "Name":"Polywoggle",
    "Alignment":"",
    "Type":"Animal",
    "Tier":2,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"Slay: I transform into a character that is one level higher than your hero.",
    "Gold Text":"Slay: I transform into an Upgraded character that is one level higher than your hero.",
    "Keywords":"Slay",
    "Combined":"Animal, Slay"
  },
  {
    "Name":"Rainbow Unicorn",
    "Alignment":"Good",
    "Type":"Animal",
    "Tier":2,
    "Attack":1,
    "Health":5,
    "Gold Attack":2,
    "Gold Health":10,
    "Text":"Your other Good characters have +1 Health.",
    "Gold Text":"Your other Good characters have +2 Health.",
    "Keywords":"",
    "Combined":"Good, Animal"
  },
  {
    "Name":"Sherwood Sureshot",
    "Alignment":"Good",
    "Type":"Princess",
    "Tier":2,
    "Attack":2,
    "Health":1,
    "Gold Attack":4,
    "Gold Health":2,
    "Text":"Ranged",
    "Gold Text":"Ranged",
    "Keywords":"Ranged",
    "Combined":"Good, Princess, Ranged"
  },
  {
    "Name":"Tiny",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":2,
    "Attack":6,
    "Health":1,
    "Gold Attack":12,
    "Gold Health":2,
    "Text":"",
    "Gold Text":"",
    "Keywords":"",
    "Combined":"Dwarf"
  },
  {
    "Name":"Wizard's Familiar",
    "Alignment":"",
    "Type":"Animal Mage",
    "Tier":2,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"When you cast a spell, I gain +1\/+1 permanently.",
    "Gold Text":"When you cast a spell, I gain +2\/+2 permanently.",
    "Keywords":"",
    "Combined":"Animal Mage"
  },
  {
    "Name":"Adventurer",
    "Alignment":"Good",
    "Type":"Princess",
    "Tier":3,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"Slay: +1 XP.",
    "Gold Text":"Slay: +2 XP.",
    "Keywords":"Slay",
    "Combined":"Good, Princess, Slay"
  },
  {
    "Name":"Brave Princess",
    "Alignment":"Good",
    "Type":"Princess",
    "Tier":3,
    "Attack":3,
    "Health":3,
    "Gold Attack":6,
    "Gold Health":6,
    "Text":"Quest: I Slay 3 enemies.",
    "Gold Text":"Quest: I Slay 3 enemies.",
    "Keywords":"Slay, Quest",
    "Combined":"Good, Princess, Slay, Quest"
  },
  {
    "Name":"Darkwood Creeper",
    "Alignment":"Evil",
    "Type":"Treant",
    "Tier":3,
    "Attack":0,
    "Health":3,
    "Gold Attack":0,
    "Gold Health":6,
    "Text":"When one of your characters survives damage, give it +1 Attack permanently.",
    "Gold Text":"When one of your characters survives damage, give it +2 Attack permanently.",
    "Keywords":"",
    "Combined":"Evil, Treant"
  },
  {
    "Name":"Dubly",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":3,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"Double bonuses to my Attack and Health.",
    "Gold Text":"Triple bonuses to my Attack and Health.",
    "Keywords":"",
    "Combined":"Dwarf"
  },
  {
    "Name":"Good Witch of the North",
    "Alignment":"Good",
    "Type":"Mage",
    "Tier":3,
    "Attack":2,
    "Health":3,
    "Gold Attack":4,
    "Gold Health":6,
    "Text":"Good Support: +2\/+3",
    "Gold Text":"Good Support: +4\/+6",
    "Keywords":"Support",
    "Combined":"Good, Mage, Support"
  },
  {
    "Name":"Hungry Hungry Hippocampus",
    "Alignment":"Good",
    "Type":"Animal",
    "Tier":3,
    "Attack":5,
    "Health":1,
    "Gold Attack":10,
    "Gold Health":2,
    "Text":"When you buy an Animal, I gain +1 Health permanently.",
    "Gold Text":"When you buy an Animal, I gain +2 Health permanently.",
    "Keywords":"",
    "Combined":"Good, Animal"
  },
  {
    "Name":"Lucky",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":3,
    "Attack":2,
    "Health":2,
    "Gold Attack":4,
    "Gold Health":4,
    "Text":"Last Breath: Reduce the cost of a random character in your next shop by 2.",
    "Gold Text":"Last Breath: Reduce the cost of a random character in your next shop by 4.",
    "Keywords":"Last Breath",
    "Combined":"Dwarf, Last Breath"
  },
  {
    "Name":"Princess Peep",
    "Alignment":"Good",
    "Type":"Princess",
    "Tier":3,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"Last Breath: Summon three 1\/1 Sheep.",
    "Gold Text":"Last Breath: Summon three 2\/2 Sheep.",
    "Keywords":"Last Breath",
    "Combined":"Good, Princess, Last Breath"
  },
  {
    "Name":"Prized Pig",
    "Alignment":"",
    "Type":"Animal",
    "Tier":3,
    "Attack":3,
    "Health":6,
    "Gold Attack":6,
    "Gold Health":12,
    "Text":"When I survive a brawl, +2 Gold.\nLast Breath: Give your opponent +1 Gold.",
    "Gold Text":"When I survive a brawl, +4 Gold.\nLast Breath: Give your opponent +2 Gold.",
    "Keywords":"Last Breath",
    "Combined":"Animal, Last Breath"
  },
  {
    "Name":"Queen of Hearts",
    "Alignment":"Evil",
    "Type":"Queen",
    "Tier":3,
    "Attack":1,
    "Health":3,
    "Gold Attack":2,
    "Gold Health":6,
    "Text":"When one of your Evil characters dies, I gain +2\/+2 this brawl.",
    "Gold Text":"When one of your Evil characters dies, I gain +4\/+4 this brawl.",
    "Keywords":"",
    "Combined":"Evil, Queen"
  },
  {
    "Name":"Romeo",
    "Alignment":"Good",
    "Type":"Prince",
    "Tier":3,
    "Attack":5,
    "Health":3,
    "Gold Attack":10,
    "Gold Health":6,
    "Text":"Last Breath: If Juliet is dead, summon her and give her +6\/+6 this brawl.",
    "Gold Text":"Last Breath: If Juliet is dead, summon her and give her +12\/+12 this brawl.",
    "Keywords":"Last Breath",
    "Combined":"Good, Prince, Last Breath"
  },
  {
    "Name":"Shadow Assassin",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":3,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"Ranged\nWhen one of your characters triggers a Slay ability, I gain +1\/+1 permanently.",
    "Gold Text":"Ranged\nWhen one of your characters triggers a Slay ability, I gain +2\/+2 permanently.",
    "Keywords":"Slay, Ranged",
    "Combined":"Evil, Monster, Slay, Ranged"
  },
  {
    "Name":"Sleeping Princess",
    "Alignment":"Good",
    "Type":"Princess",
    "Tier":3,
    "Attack":0,
    "Health":8,
    "Gold Attack":0,
    "Gold Health":16,
    "Text":"I wake up when you cast a spell on me. (+8 Attack)",
    "Gold Text":"I wake up when you cast a spell on me. (+16 Attack)",
    "Keywords":"",
    "Combined":"Good, Princess"
  },
  {
    "Name":"Spell Weaver",
    "Alignment":"Evil",
    "Type":"Mage",
    "Tier":3,
    "Attack":1,
    "Health":3,
    "Gold Attack":2,
    "Gold Health":6,
    "Text":"Ranged\nWhen you cast a spell, I gain +1 Attack permanently.",
    "Gold Text":"Ranged\nWhen you cast a spell, I gain +2 Attack permanently.",
    "Keywords":"Ranged",
    "Combined":"Evil, Mage, Ranged"
  },
  {
    "Name":"The White Stag",
    "Alignment":"Good",
    "Type":"Animal",
    "Tier":3,
    "Attack":3,
    "Health":3,
    "Gold Attack":6,
    "Gold Health":6,
    "Text":"When I attack, give the characters behind me +3\/+3 this brawl.",
    "Gold Text":"When I attack, give the characters behind me +6\/+6 this brawl.",
    "Keywords":"",
    "Combined":"Good, Animal"
  },
  {
    "Name":"Trojan Donkey",
    "Alignment":"Good",
    "Type":"Animal",
    "Tier":3,
    "Attack":1,
    "Health":5,
    "Gold Attack":2,
    "Gold Health":10,
    "Text":"When I survive damage, summon a random character.",
    "Gold Text":"When I survive damage, summon a random Upgraded character.",
    "Keywords":"",
    "Combined":"Good, Animal"
  },
  {
    "Name":"Tweedle Dee",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":3,
    "Attack":4,
    "Health":1,
    "Gold Attack":8,
    "Gold Health":2,
    "Text":"Last Breath: Summon a 1\/4 Tweedle Dum.",
    "Gold Text":"Last Breath: Summon a2\/8 Tweedle Dum.",
    "Keywords":"Last Breath",
    "Combined":"Dwarf, Last Breath"
  },
  {
    "Name":"Vain-Pire",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":3,
    "Attack":4,
    "Health":4,
    "Gold Attack":8,
    "Gold Health":8,
    "Text":"Slay: +4 Health this brawl.",
    "Gold Text":"Slay: +8 Health this brawl.",
    "Keywords":"Slay",
    "Combined":"Evil, Monster, Slay"
  },
  {
    "Name":"Wicked Witch of the West",
    "Alignment":"Evil",
    "Type":"Mage",
    "Tier":3,
    "Attack":3,
    "Health":2,
    "Gold Attack":6,
    "Gold Health":4,
    "Text":"Evil Support: +3\/+2",
    "Gold Text":"Evil Support: +6\/+4",
    "Keywords":"Support",
    "Combined":"Evil, Mage, Support"
  },
  {
    "Name":"Bearded Vulture",
    "Alignment":"Evil",
    "Type":"Animal",
    "Tier":4,
    "Attack":3,
    "Health":3,
    "Gold Attack":6,
    "Gold Health":6,
    "Text":"When one of your Animals dies, I gain +3\/+3 this brawl.",
    "Gold Text":"When one of your Animals dies, I gain +6\/+6 this brawl.",
    "Keywords":"",
    "Combined":"Evil, Animal"
  },
  {
    "Name":"Bossy",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":4,
    "Attack":4,
    "Health":4,
    "Gold Attack":8,
    "Gold Health":8,
    "Text":"Your other Dwarves have +2\/+2.",
    "Gold Text":"Your other Dwarves have +4\/+4.",
    "Keywords":"",
    "Combined":"Dwarf"
  },
  {
    "Name":"Broc Lee",
    "Alignment":"Evil",
    "Type":"Treant",
    "Tier":4,
    "Attack":0,
    "Health":15,
    "Gold Attack":0,
    "Gold Health":30,
    "Text":"When I survive damage, I gain +10 Attack this brawl.",
    "Gold Text":"When I survive damage, I gain +20 Attack this brawl.",
    "Keywords":"",
    "Combined":"Evil, Treant"
  },
  {
    "Name":"Copycat",
    "Alignment":"",
    "Type":"Animal",
    "Tier":4,
    "Attack":4,
    "Health":1,
    "Gold Attack":8,
    "Gold Health":2,
    "Text":"I have the Last Breath abilities of the characters behind me.",
    "Gold Text":"I have the Last Breath abilities of the characters behind me and they trigger twice.",
    "Keywords":"Last Breath",
    "Combined":"Animal, Last Breath"
  },
  {
    "Name":"Court Wizard",
    "Alignment":"Good",
    "Type":"Mage",
    "Tier":4,
    "Attack":4,
    "Health":2,
    "Gold Attack":8,
    "Gold Health":4,
    "Text":"Ranged\nWhen one of your Princes or Princesses is attacked and killed, I make a bonus attack.",
    "Gold Text":"Ranged\nWhen one of your Princes or Princesses is attacked and killed, I make a bonus attack.",
    "Keywords":"Ranged",
    "Combined":"Good, Mage, Ranged"
  },
  {
    "Name":"Fairy Godmother",
    "Alignment":"Good",
    "Type":"Fairy",
    "Tier":4,
    "Attack":2,
    "Health":2,
    "Gold Attack":4,
    "Gold Health":4,
    "Text":"When one of your Good characters dies, give your Good characters +2 Health this brawl.",
    "Gold Text":"When one of your Good characters dies, give your Good characters +4 Health this brawl.",
    "Keywords":"",
    "Combined":"Good, Fairy"
  },
  {
    "Name":"Friendly Spirit",
    "Alignment":"Good",
    "Type":"Monster",
    "Tier":4,
    "Attack":3,
    "Health":3,
    "Gold Attack":6,
    "Gold Health":6,
    "Text":"Last Breath: Give my Attack and Health to one of your characters this brawl.",
    "Gold Text":"Last Breath: Give double my Attack and Health to one of your characters this brawl.",
    "Keywords":"Last Breath",
    "Combined":"Good, Monster, Last Breath"
  },
  {
    "Name":"Greedy",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":4,
    "Attack":3,
    "Health":6,
    "Gold Attack":6,
    "Gold Health":12,
    "Text":"When I survive damage, +1 Gold.",
    "Gold Text":"When I survive damage, +2 Gold.",
    "Keywords":"",
    "Combined":"Dwarf"
  },
  {
    "Name":"Grim Soul",
    "Alignment":"",
    "Type":"Monster",
    "Tier":4,
    "Attack":5,
    "Health":1,
    "Gold Attack":10,
    "Gold Health":2,
    "Text":"Last Breath: Trigger a Slay ability on one of your characters.",
    "Gold Text":"Last Breath: Trigger a Slay ability on one of your characters twice.",
    "Keywords":"Slay, Last Breath",
    "Combined":"Monster, Slay, Last Breath"
  },
  {
    "Name":"Heartwood Elder",
    "Alignment":"",
    "Type":"Treant",
    "Tier":4,
    "Attack":2,
    "Health":9,
    "Gold Attack":4,
    "Gold Health":18,
    "Text":"Treant Support: At the start of each brawl, gain +1\/+2 permanently.",
    "Gold Text":"Treant Support: At the start of each brawl, gain +2\/+4 permanently.",
    "Keywords":"Support",
    "Combined":"Treant, Support"
  },
  {
    "Name":"Juliet",
    "Alignment":"Good",
    "Type":"Princess",
    "Tier":4,
    "Attack":6,
    "Health":6,
    "Gold Attack":12,
    "Gold Health":12,
    "Text":"",
    "Gold Text":"",
    "Keywords":"",
    "Combined":"Good, Princess"
  },
  {
    "Name":"Lady of the Lake",
    "Alignment":"Good",
    "Type":"Mage",
    "Tier":4,
    "Attack":1,
    "Health":3,
    "Gold Attack":2,
    "Gold Health":6,
    "Text":"Ranged\nSupport: +5 Health",
    "Gold Text":"Ranged\nSupport: +10 Health",
    "Keywords":"Support, Ranged",
    "Combined":"Good, Mage, Support, Ranged"
  },
  {
    "Name":"Lightning Dragon",
    "Alignment":"",
    "Type":"Dragon",
    "Tier":4,
    "Attack":8,
    "Health":1,
    "Gold Attack":16,
    "Gold Health":2,
    "Text":"Flying\nAt the start each brawl, I make a bonus attack.",
    "Gold Text":"Flying\nAt the start each brawl, I make a bonus attack.",
    "Keywords":"Flying",
    "Combined":"Dragon, Flying"
  },
  {
    "Name":"Medusa",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":4,
    "Attack":3,
    "Health":3,
    "Gold Attack":6,
    "Gold Health":6,
    "Text":"When I attack a character, first transform it into a 0\/6 Statue.",
    "Gold Text":"When I attack a character, first transform it into a 0\/3 Statue.",
    "Keywords":"",
    "Combined":"Evil, Monster"
  },
  {
    "Name":"Prince Arthur",
    "Alignment":"Good",
    "Type":"Prince",
    "Tier":4,
    "Attack":4,
    "Health":5,
    "Gold Attack":8,
    "Gold Health":10,
    "Text":"At the start of each brawl, give your Upgraded Princes and Princesses +2\/+2 permanently.",
    "Gold Text":"At the start of each brawl, give your Upgraded Princes and Princesses +4\/+4 permanently.",
    "Keywords":"",
    "Combined":"Good, Prince"
  },
  {
    "Name":"Princess Pea",
    "Alignment":"Good",
    "Type":"Princess",
    "Tier":4,
    "Attack":4,
    "Health":4,
    "Gold Attack":8,
    "Gold Health":8,
    "Text":"I have +4\/+4 for each character Supporting me.",
    "Gold Text":"I have +8\/+8 for each character Supporting me.",
    "Keywords":"Support",
    "Combined":"Good, Princess, Support"
  },
  {
    "Name":"Princess Wight",
    "Alignment":"Evil",
    "Type":"Princess",
    "Tier":4,
    "Attack":2,
    "Health":8,
    "Gold Attack":4,
    "Gold Health":16,
    "Text":"When one of your Dwarves dies, I gain +1\/+1 permanently.\nQuest: Buy seven Dwarves.",
    "Gold Text":"When one of your Dwarves dies, I gain +2\/+2 permanently.\nQuest: Buy seven Dwarves.",
    "Keywords":"Quest",
    "Combined":"Evil, Princess, Quest"
  },
  {
    "Name":"Puff Puff",
    "Alignment":"Good",
    "Type":"Puff Puff",
    "Tier":4,
    "Attack":5,
    "Health":5,
    "Gold Attack":10,
    "Gold Health":10,
    "Text":"I don't upgrade with other Puff Puffs.\nLast Breath: Give all your Puff Puffs everywhere +1\/+1 Permanently.",
    "Gold Text":"Last Breath: Give all your Puff Puffs everywhere +2\/+2 permanently.",
    "Keywords":"Last Breath",
    "Combined":"Good, Puff Puff, Last Breath"
  },
  {
    "Name":"Riverwish Mermaid",
    "Alignment":"Good",
    "Type":"Princess",
    "Tier":4,
    "Attack":4,
    "Health":4,
    "Gold Attack":8,
    "Gold Health":8,
    "Text":"Support: Give characters in front of me \"Slay: +1\/+1 permanently.",
    "Gold Text":"Support: \"Slay: +2\/+2 permanently.",
    "Keywords":"Support, Slay",
    "Combined":"Good, Princess, Support, Slay"
  },
  {
    "Name":"Sheep in Wolf's Clothing",
    "Alignment":"Evil",
    "Type":"Animal",
    "Tier":4,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"Last Breath: Summon a 5\/5 Sheep.",
    "Gold Text":"Last Breath: Summon a 10\/10 Sheep",
    "Keywords":"Last Breath",
    "Combined":"Evil, Animal, Last Breath"
  },
  {
    "Name":"Sporko",
    "Alignment":"Evil",
    "Type":"Mage",
    "Tier":4,
    "Attack":1,
    "Health":3,
    "Gold Attack":2,
    "Gold Health":6,
    "Text":"Ranged\nSupport: +5 Attack.",
    "Gold Text":"Ranged\nSupport: +10 Attack.",
    "Keywords":"Support, Ranged",
    "Combined":"Evil, Mage, Support, Ranged"
  },
  {
    "Name":"The Chupacabra",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":4,
    "Attack":5,
    "Health":5,
    "Gold Attack":10,
    "Gold Health":10,
    "Text":"Slay: +1\/+2 permanently.",
    "Gold Text":"Slay: +2\/+4 permanently.",
    "Keywords":"Slay",
    "Combined":"Evil, Monster, Slay"
  },
  {
    "Name":"The Nutcracker",
    "Alignment":"Good",
    "Type":"Treant Prince",
    "Tier":4,
    "Attack":2,
    "Health":10,
    "Gold Attack":4,
    "Gold Health":20,
    "Text":"Quest: I survive damage 5 times.",
    "Gold Text":"Quest: I survive damage 5 times.",
    "Keywords":"Quest",
    "Combined":"Good, Treant Prince, Quest"
  },
  {
    "Name":"Angry",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":5,
    "Attack":4,
    "Health":10,
    "Gold Attack":8,
    "Gold Health":20,
    "Text":"When I survive damage, give all your Dwarves +2\/+2 this brawl.",
    "Gold Text":"When I survive damage, give all your Dwarves +4\/+4 this brawl.",
    "Keywords":"",
    "Combined":"Dwarf"
  },
  {
    "Name":"Aon",
    "Alignment":"Evil",
    "Type":"Mage",
    "Tier":5,
    "Attack":4,
    "Health":12,
    "Gold Attack":8,
    "Gold Health":24,
    "Text":"When you cast a spell, give your Mages +1 Attack permanently.",
    "Gold Text":"When you cast a spell, give your Mages +2 Attack permanently.",
    "Keywords":"",
    "Combined":"Evil, Mage"
  },
  {
    "Name":"Baba Yaga",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":5,
    "Attack":3,
    "Health":6,
    "Gold Attack":6,
    "Gold Health":12,
    "Text":"Ranged\nSupport: +3 Attack and double Slay abilities.",
    "Gold Text":"Ranged\nSupport: +6 Attack and double Slay abilities.",
    "Keywords":"Support, Slay, Ranged",
    "Combined":"Evil, Monster, Support, Slay, Ranged"
  },
  {
    "Name":"Baby Bear",
    "Alignment":"Good",
    "Type":"Animal",
    "Tier":5,
    "Attack":1,
    "Health":1,
    "Gold Attack":2,
    "Gold Health":2,
    "Text":"Last Breath: Summon a 2\/2 Papa Bear (that summons a 4\/4 Mama Bear).",
    "Gold Text":"Last Breath: Summon a 4\/4 Papa Bear (that summons an 8\/8 Mama Bear).",
    "Keywords":"Last Breath",
    "Combined":"Good, Animal, Last Breath"
  },
  {
    "Name":"Cupid",
    "Alignment":"Good",
    "Type":"Fairy",
    "Tier":5,
    "Attack":1,
    "Health":10,
    "Gold Attack":2,
    "Gold Health":20,
    "Text":"Flying, Ranged\nWhen I attack a character, it attacks a character on its own side.",
    "Gold Text":"Flying, Ranged\nWhen I attack a character, it attacks a character on its own side.",
    "Keywords":"Flying, Ranged",
    "Combined":"Good, Fairy, Flying, Ranged"
  },
  {
    "Name":"Lancelot",
    "Alignment":"Good",
    "Type":"Prince",
    "Tier":5,
    "Attack":7,
    "Health":7,
    "Gold Attack":14,
    "Gold Health":14,
    "Text":"Slay: +2\/+2 permanently.\nQuest: I have at least 25 Attack or Health during a brawl.",
    "Gold Text":"Slay: +4\/+4 permanently.\nQuest: I have at least 25 Attack or Health during a brawl.",
    "Keywords":"Slay, Quest",
    "Combined":"Good, Prince, Slay, Quest"
  },
  {
    "Name":"Monster Book",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":5,
    "Attack":4,
    "Health":4,
    "Gold Attack":8,
    "Gold Health":8,
    "Text":"Last Breath: Cast a random spell on an enemy character.",
    "Gold Text":"Last Breath: Cast a random spell on an enemy character twice.",
    "Keywords":"Last Breath",
    "Combined":"Evil, Monster, Last Breath"
  },
  {
    "Name":"Nian, Sea Terror",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":5,
    "Attack":8,
    "Health":8,
    "Gold Attack":16,
    "Gold Health":16,
    "Text":"I only need two copies to Upgrade.",
    "Gold Text":"",
    "Keywords":"",
    "Combined":"Evil, Monster"
  },
  {
    "Name":"Rotten Appletree",
    "Alignment":"Evil",
    "Type":"Treant",
    "Tier":5,
    "Attack":0,
    "Health":15,
    "Gold Attack":0,
    "Gold Health":30,
    "Text":"When I'm attacked, first reduce the attacker's Health to 1.",
    "Gold Text":"When I'm attacked, first reduce the attacker's Health to 1.",
    "Keywords":"",
    "Combined":"Evil, Treant"
  },
  {
    "Name":"Soltak Ancient",
    "Alignment":"Good",
    "Type":"Treant",
    "Tier":5,
    "Attack":0,
    "Health":20,
    "Gold Attack":0,
    "Gold Health":30,
    "Text":"Prevent all damage to characters behind me, except for when they are attacking.",
    "Gold Text":"Prevent all damage to characters behind me, except for when they are attacking.",
    "Keywords":"",
    "Combined":"Good, Treant"
  },
  {
    "Name":"Southern Siren",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":5,
    "Attack":8,
    "Health":8,
    "Gold Attack":16,
    "Gold Health":16,
    "Text":"Slay: Summon an exact copy of the slain character.",
    "Gold Text":"Slay: Summon an Upgraded exact copy of the slain character.",
    "Keywords":"Slay",
    "Combined":"Evil, Monster, Slay"
  },
  {
    "Name":"Wombats in Disguise",
    "Alignment":"",
    "Type":"Animal",
    "Tier":5,
    "Attack":4,
    "Health":4,
    "Gold Attack":8,
    "Gold Health":8,
    "Text":"Last Breath: Summon a random level 6 character.",
    "Gold Text":"Last Breath: Summon a random Upgraded level 6 character.",
    "Keywords":"Last Breath",
    "Combined":"Animal, Last Breath"
  },
  {
    "Name":"Wretched Mummy",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":5,
    "Attack":4,
    "Health":1,
    "Gold Attack":8,
    "Gold Health":2,
    "Text":"Last Breath: Deal 4 damage to all enemy characters.",
    "Gold Text":"Last Breath: Deal 8 damage to all enemy characters.",
    "Keywords":"Last Breath",
    "Combined":"Evil, Monster, Last Breath"
  },
  {
    "Name":"Ashwood Elm",
    "Alignment":"Evil",
    "Type":"Treant",
    "Tier":6,
    "Attack":0,
    "Health":20,
    "Gold Attack":0,
    "Gold Health":40,
    "Text":"At the start of each brawl, give your Treants +Attack equal to my Health this brawl.",
    "Gold Text":"At the start of each brawl, give your Treants +Attack equal to double my Health this brawl.",
    "Keywords":"",
    "Combined":"Evil, Treant"
  },
  {
    "Name":"Bearstein",
    "Alignment":"Good",
    "Type":"Animal",
    "Tier":6,
    "Attack":7,
    "Health":10,
    "Gold Attack":14,
    "Gold Health":20,
    "Text":"Your other Animals have +2\/+2.\nWhen you summon an Animal during a brawl, double its Attack and Health.",
    "Gold Text":"Your other Animals have +4\/+4.\nWhen you summon an Animal during a brawl, triple its Attack and Health.",
    "Keywords":"",
    "Combined":"Good, Animal"
  },
  {
    "Name":"Doombreath",
    "Alignment":"Evil",
    "Type":"Dragon",
    "Tier":6,
    "Attack":6,
    "Health":6,
    "Gold Attack":12,
    "Gold Health":12,
    "Text":"I also damage the characters behind the character I attack.",
    "Gold Text":"I also damage the characters behind the character I attack.",
    "Keywords":"",
    "Combined":"Evil, Dragon"
  },
  {
    "Name":"Echowood",
    "Alignment":"",
    "Type":"Treant",
    "Tier":6,
    "Attack":0,
    "Health":1,
    "Gold Attack":0,
    "Gold Health":2,
    "Text":"When another one of your characters gains Attack or Health during a brawl, so do I.",
    "Gold Text":"When another one of your characters gains Attack or Health during a brawl, I gain twice as much.",
    "Keywords":"",
    "Combined":"Treant"
  },
  {
    "Name":"Good Boy",
    "Alignment":"Good",
    "Type":"Animal",
    "Tier":6,
    "Attack":5,
    "Health":5,
    "Gold Attack":10,
    "Gold Health":10,
    "Text":"Last Breath: Give your Good characters my Attack and Health this brawl.",
    "Gold Text":"Last Breath: Give your Good characters double my Attack and Health this brawl.",
    "Keywords":"Last Breath",
    "Combined":"Good, Animal, Last Breath"
  },
  {
    "Name":"Grumblegore",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":6,
    "Attack":10,
    "Health":5,
    "Gold Attack":20,
    "Gold Health":10,
    "Text":"Ranged\nSupport: +10 Attack",
    "Gold Text":"Ranged\nSupport: +20 Attack",
    "Keywords":"Support, Ranged",
    "Combined":"Evil, Monster, Support, Ranged"
  },
  {
    "Name":"Hercules",
    "Alignment":"Good",
    "Type":"Prince",
    "Tier":6,
    "Attack":20,
    "Health":20,
    "Gold Attack":40,
    "Gold Health":40,
    "Text":"Quest: I deal 100 damage.",
    "Gold Text":"Quest: I deal 100 damage.",
    "Keywords":"Quest",
    "Combined":"Good, Prince, Quest"
  },
  {
    "Name":"Jormungand",
    "Alignment":"",
    "Type":"Monster",
    "Tier":6,
    "Attack":20,
    "Health":20,
    "Gold Attack":40,
    "Gold Health":40,
    "Text":"Slay: +20\/+20 this brawl.",
    "Gold Text":"Slay: +40\/+40 this brawl.",
    "Keywords":"Slay",
    "Combined":"Monster, Slay"
  },
  {
    "Name":"Lordy",
    "Alignment":"",
    "Type":"Dwarf",
    "Tier":6,
    "Attack":7,
    "Health":7,
    "Gold Attack":14,
    "Gold Health":14,
    "Text":"At the start of each brawl, give your Dwarves +2\/+2 this brawl for each Dwarf you have.",
    "Gold Text":"At the start of each brawl, give your Dwarves +4\/+4 this brawl for each Dwarf you have.",
    "Keywords":"",
    "Combined":"Dwarf"
  },
  {
    "Name":"Pumpkin King",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":6,
    "Attack":5,
    "Health":5,
    "Gold Attack":10,
    "Gold Health":10,
    "Text":"Last Breath: For each of your dead Evil characters, summon a random lower level Evil character.",
    "Gold Text":"Last Breath: For each of your dead Evil characters, summon a random Upgraded lower level Evil character.",
    "Keywords":"Last Breath",
    "Combined":"Evil, Monster, Last Breath"
  },
  {
    "Name":"Robin Wood",
    "Alignment":"Good",
    "Type":"Treant",
    "Tier":6,
    "Attack":7,
    "Health":10,
    "Gold Attack":14,
    "Gold Health":20,
    "Text":"Ranged\nAt the start of each brawl, give the strongest enemy -15 Attack, and your weakest character +15 Attack.",
    "Gold Text":"Ranged\nAt the start of each brawl, give the strongest enemy -30 Attack, and your weakest character +30 Attack.",
    "Keywords":"Ranged",
    "Combined":"Good, Treant, Ranged"
  },
  {
    "Name":"The Green Knight",
    "Alignment":"Good",
    "Type":"Treant",
    "Tier":6,
    "Attack":10,
    "Health":30,
    "Gold Attack":20,
    "Gold Health":60,
    "Text":"Support: +10 Health",
    "Gold Text":"Support: +20 Health",
    "Keywords":"Support",
    "Combined":"Good, Treant, Support"
  },
  {
    "Name":"The Oni King",
    "Alignment":"Evil",
    "Type":"Monster",
    "Tier":6,
    "Attack":13,
    "Health":13,
    "Gold Attack":26,
    "Gold Health":26,
    "Text":"When one of your Monsters attacks, give it +10\/+10 this brawl.",
    "Gold Text":"When one of your Monsters attacks, give it +20\/+20 this brawl.",
    "Keywords":"",
    "Combined":"Evil, Monster"
  },
  {
    "Name":"The Storm King",
    "Alignment":"",
    "Type":"Mage",
    "Tier":6,
    "Attack":2,
    "Health":2,
    "Gold Attack":4,
    "Gold Health":4,
    "Text":"+2\/+2 for each spell you have cast this game.",
    "Gold Text":"+4\/+4 for each spell you have cast this game.",
    "Keywords":"",
    "Combined":"Mage"
  },
  {
    "Name":"Three Big Pigs",
    "Alignment":"Evil",
    "Type":"Animal",
    "Tier":6,
    "Attack":9,
    "Health":9,
    "Gold Attack":18,
    "Gold Health":18,
    "Text":"Last Breath: Summon three 3\/3 Pigs.",
    "Gold Text":"Last Breath: Summon three 6\/6 Pigs.",
    "Keywords":"Last Breath",
    "Combined":"Evil, Animal, Last Breath"
  }
]
export default minions;